# Generated by Django 5.0.1 on 2024-01-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(db_column='id_boleta', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=20)),
                ('total', models.IntegerField()),
                ('metodo_pago', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=10)),
                ('cliente', models.ForeignKey(db_column='Rut', on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
