# Generated by Django 5.0.1 on 2024-01-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('anno_fab', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado')], max_length=5)),
                ('categoria', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=200)),
            ],
        ),
    ]
