# Generated by Django 5.0.1 on 2024-01-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('fec_nac', models.DateField()),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('contrasena', models.CharField(max_length=15)),
                ('id_producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
